URLS = [
  'http://www.tv.com/30-rock/show/58326/episode.html?season=All', # 30 Rock
  'http://www.tv.com/archer/show/77555/episode.html?season=All', # Archer
  'http://www.tv.com/battlestar-galactica-2003/show/23557/episode.html?season=All', # Battlestar Galactica
  'http://www.tv.com/the-big-bang-theory/show/58056/episode.html?season=All', # The Big Bang Theory
  'http://www.tv.com/chuck/show/68724/episode.html?season=All', # Chuck
  'http://www.tv.com/doctor-who/show/34391/episode.html?season=All', # Doctor Who
  'http://www.tv.com/family-guy/show/348/episode.html?&season=All', # Family Guy
  'http://www.tv.com/firefly/show/7097/episode.html?season=All', # Firefly
  'http://www.tv.com/flight-of-the-conchords/show/68719/episode.html?All&season=All', # Flight of the Conchords
  'http://www.tv.com/friends/show/71/episode.html?season=All', # Friends
  'http://www.tv.com/fringe/show/75146/episode.html?season=All', # Fringe
  'http://www.tv.com/greys-anatomy/show/24440/episode.html?season=All', # Grey's Anatomy
  'http://www.tv.com/house/show/22374/episode.html?season=All', # House
  'http://www.tv.com/how-i-met-your-mother/show/33700/episode.html?season=All', # How I Met Your Mother
  'http://www.tv.com/lost/show/24313/episode.html?season=All', # Lost
  'http://www.tv.com/the-middle/show/68657/episode.html?season=All', # Middle, The
  'http://www.tv.com/ncis/show/16772/episode.html?season=All', # NCIS
  'http://www.tv.com/ncis-los-angeles/show/76607/episode.html?season=All', # NCIS: Los Angeles
  'http://www.tv.com/nikita/show/78642/episode.html?season=All', # Nikita
  'http://www.tv.com/the-office/show/22343/episode.html?season=All', # The Office
  'http://www.tv.com/scrubs/show/3613/episode.html?season=All', # Scrubs
  'http://www.tv.com/seinfeld/show/112/episode.html?season=All', # Seinfeld
  'http://www.tv.com/the-simpsons/show/146/episode.html?season=All', # The Simpsons
  'http://www.tv.com/south-park/show/344/episode.html?season=All', # South Park
  'http://www.tv.com/star-trek/show/633/episode.html?season=All', # Star Trek
  'http://www.tv.com/star-trek-deep-space-nine/show/166/episode.html?season=All', # Star Trek: Deep Space Nine
  'http://www.tv.com/star-trek-enterprise/show/2498/episode.html?season=All', # Star Trek: Enterprise
  'http://www.tv.com/star-trek-the-next-generation/show/137/episode.html?season=All', # Star Trek: The Next Generation
  'http://www.tv.com/star-trek-voyager/show/274/episode.html?season=All', # Star Trek: Voyager Season
  'http://www.tv.com/supernatural/show/30144/episode.html?season=All', # Supernatural
  'http://www.tv.com/the-x-files/show/61/episode.html?season=All' # The X-Files
]